[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_ASSET_BASE_URL = "https://shankarya-assets-2025.s3.us-east-1.amazonaws.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
